### ISSUE TITLE
feat: Describe the flow of interaction between Kakarot and an Ethereum Account Abstraction account on Starknet

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#388] opened 2022-12-21 09:45 UTC
# Feature Request

**Describe the Feature Request**

We recently chose to go with Account Abstraction to allow users to interact with Kakarot using their EVM private key.

The preferred end goal (long-term vision) would be that:
- someone could use their private key and a metamask extension to send a transaction to Kakarot.

This implies that their signature must be verifiable by an Eth Account Abstraction on Starknet. 

In this issue, we need the contributor to explore deeply and in very technical terms the implications of the flow that results from these choices.

## To summarize:
- Kakarot will use an Eth Account Abstraction to emulate EVM signature behaviour on Starknet.
- What are the challenges linked to it?

## Tasks:
- Check the production readiness of the OZ Ethereum Account Abstraction contract.
- Check the feasibility of signature verification on Starknet (an EVM transaction crafted by any library ether.js or metamask) readable for Starknet? -> transaction encoding and decoding on-chain?
- Check gas implications? What does it mean to send a gasLimit, a gas tip etc. in an EVM tx compared to Kakarot?
- How to avoid having multiple accounts controlled by the same Ethereum address

**Comment by Th0rgal** [comment] 2022-12-21 10:00
Hey,

Here is a few ideas about * How to avoid having multiple accounts controlled by the same Ethereum address *:

1) The address of a Starknet account is deterministic, it might be feasible to make it so it depends on the underlying ethereum address which controls the account. That way we would keep 1 public key = 1 account and we could cheaply resolve an ethereum address to an account (we would just have to hash the same way we do to compute the contract address).

2) @abdelhamidbakhta controls kakarot.stark, which can be connected to a smartcontract to handle the resolving of subdomains. This would allow to automatically map something like 0x12345.kakarot.stark to the Starknet Account controled by 0x12345 address.

**Comment by Eikix** [comment] 2022-12-21 13:50
I'm not sure I understand!

I take the following facts as given inputs:
- user A has an existing private key on Ethereum
- user A wants to sign a Kakarot tx with this private key.
- user A must have an Ethereum AA on Starknet that is bound to the same private key as on other EVMs. This Ethereum AA must have one "default" or one "unique" address / public key, so that 1 eth private key = 1 eth address.
- user A's Ethereum AA on Starknet must be able to receive, decode this tx and run EVM sig verification on it.

**Comment by Flydexo** [comment] 2022-12-24 00:55
And currenty, was does the BALANCE OPCODE return ? The balance of ETH on the starknet network or "ETH" on Kakarot (if it exists)

**Comment by Flydexo** [comment] 2022-12-24 01:19
Update: it returns the balance of the native ERC20 set by a contract function on the Kakarot contract.
Current name: Kakarot Token (KKT)

**Comment by Flydexo** [comment] 2022-12-27 22:17
Different user flows we discussed on telegram:

Note: for the account abstraction contracts we user the `__validate__` method which allows the contract to validate a custom transaction (even if not signed with starknet account). More information [here](https://docs.starknet.io/documentation/architecture_and_concepts/Account_Abstraction/approach/)

# 1. RPC is a signer and is refunded from fees with a wrapped token (not best idea)

|✅ Pros|❌ Cons|
|-----|-----|
|No need for the user to interact with starknet|RPC needs to hold a private key with funds |
||Fee complexity (Kakarot + Starknet)|
||Less security with a token bridge|

![image_2022-12-27_22-01-45](https://user-images.githubusercontent.com/66029824/209726607-08dc640f-8437-40e4-a6b4-3b950a95f0db.png)

# 2. Each user has an account abstraction contract

|✅ Pros|❌ Cons|
|-----|-----|
|RPC is trustless (should be)|User needs a starknet account for the setup|
|Fees are managed by starknet|Implement an EVM account abstraction & signature validation|
|No wrapped token||

<img width="958" alt="Screenshot 2022-12-27 at 22 43 42" src="https://user-images.githubusercontent.com/66029824/209726889-2c599f23-f4f3-4d45-8575-a0e76c9b2a90.png">

# 3. Account abstraction managed by Kakarot

|✅ Pros|❌ Cons|
|-----|-----|
|RPC is trustless (should be)|User needs a starknet account for the setup|
|Fees are managed by starknet|Implement an EVM account abstraction & signature validation|
|No wrapped token|Single point of failure|
|Simpler than a contract = an account||

<img width="958" alt="Screenshot 2022-12-27 at 23 04 39" src="https://user-images.githubusercontent.com/66029824/209727318-5016d947-8a15-488a-9c39-e2d27d4912b5.png">

**Comment by Th0rgal** [comment] 2022-12-28 06:52
> Different user flows we discussed on telegram:
> 
> 
> 
> Note: for the account abstraction contracts we user the `__validate__` method which allows the contract to validate a custom transaction (even if not signed with starknet account). More information [here](https://docs.starknet.io/documentation/architecture_and_concepts/Account_Abstraction/approach/)
> 
> 
> 
> # 1. RPC is a signer and is refunded from fees with a wrapped token (not best idea)
> 
> 
> 
> |✅ Pros|❌ Cons|
> 
> |-----|-----|
> 
> |No need for the user to interact with starknet|RPC needs to hold a private key with funds |
> 
> ||Fee complexity (Kakarot + Starknet)|
> 
> ||Less security with a token bridge|
> 
> 
> 
> ![image_2022-12-27_22-01-45](https://user-images.githubusercontent.com/66029824/209726607-08dc640f-8437-40e4-a6b4-3b950a95f0db.png)
> 
> 
> 
> # 2. Each user has an account abstraction contract
> 
> 
> 
> |✅ Pros|❌ Cons|
> 
> |-----|-----|
> 
> |RPC is trustless (should be)|User needs a starknet account for the setup|
> 
> |Fees are managed by starknet|Implement an EVM account abstraction & signature validation|
> 
> |No wrapped token||
> 
> 
> 
> <img width="958" alt="Screenshot 2022-12-27 at 22 43 42" src="https://user-images.githubusercontent.com/66029824/209726889-2c599f23-f4f3-4d45-8575-a0e76c9b2a90.png">
> 
> 
> 
> # 3. Account abstraction managed by Kakarot
> 
> 
> 
> |✅ Pros|❌ Cons|
> 
> |-----|-----|
> 
> |RPC is trustless (should be)|User needs a starknet account for the setup|
> 
> |Fees are managed by starknet|Implement an EVM account abstraction & signature validation|
> 
> |No wrapped token|Single point of failure|
> 
> |Simpler than a contract = an account||
> 
> 
> 
> <img width="958" alt="Screenshot 2022-12-27 at 23 04 39" src="https://user-images.githubusercontent.com/66029824/209727318-5016d947-8a15-488a-9c39-e2d27d4912b5.png">
> 
> 

Hey, the third option looks like the "1 account to rule them all" described here. I'm not sure to understand why a StarkNet Account would be required for the setup.

**Comment by Flydexo** [comment] 2022-12-28 08:16
For what you have described here:

```It would be necessary to add to the contract a deposit(address, amount) function that would allow a classic Starknet account to deposit a certain amount of ether to an Ethereum address on the portal. In the same fashion it would probably be a good idea to add withdraw function to allow moving funds back to Starknet (that looks like a free secure bridge).````

Because the user needs to fund his account portal with starknet ETH

**Comment by Th0rgal** [comment] 2022-12-28 09:55
> For what you have described here:
> 
> `It would be necessary to add to the contract a deposit(address, amount) function that would allow a classic Starknet account to deposit a certain amount of ether to an Ethereum address on the portal. In the same fashion it would probably be a good idea to add withdraw function to allow moving funds back to Starknet (that looks like a free secure bridge).`
> 
> Because the user needs to fund his account portal with starknet ETH. Kakarot won't have inner fees, all fees are starknet network fees.

Hmm, as I see it, the starknet ETH would only be owned by the single kakarot account contract. Kakarot users would own a share of it, this would be their kakarot ETH balance. When they would perform a transaction trough the single kakarot account contract, it would debit ETH from the kakarot account and this should be reflected in their kakarot balance (but to do so, we need to estimate the tx cost). What that ``deposit`` function means is that you could bridge starknet ETH to kakarot in an easy way, but you could also just get started by asking an existing kakarot user to send you some ETH directly on kakarot, like on any other EVM.
Does that make sense? :)

**Comment by Flydexo** [comment] 2022-12-28 10:54
Ok got it, so yes the difficult part will be getting the cost of the starknet tx inside the kakarot contract

**Comment by Eikix** [comment] 2022-12-28 15:37
My understanding: 

![telegram-cloud-photo-size-4-5863711381289811397-y](https://user-images.githubusercontent.com/66871571/209836116-f90a0d89-e921-4ca8-a33f-9dff9a02c100.jpg)

**Comment by Flydexo** [comment] 2022-12-31 18:07
Here is the detailed workflow of how an EVM transaction will be handled
![Tx handling flow (1)](https://user-images.githubusercontent.com/66029824/210152153-021d8045-6ac8-4edb-b29e-58be891ad78b.png)

**Comment by ClementWalter** [comment] 2023-01-02 16:23
I'm wondering if a deterministic computing of the corresponding starknet address from an EVM address would lead to potential cybersquatting

**Comment by Eikix** [comment] 2023-01-02 16:53
> I'm wondering if a deterministic computing of the corresponding starknet address from an EVM address would lead to potential cybersquatting

How so? Could you elaborate?

**Comment by ClementWalter** [comment] 2023-01-02 17:03
> > I'm wondering if a deterministic computing of the corresponding starknet address from an EVM address would lead to potential cybersquatting
> 
> How so? Could you elaborate?

just talked with @Flydexo in mp; I was unaware of the usage of a single `Deployer` contract to deploy kakarot's AccountContracts using `deploy_from_zero=FALSE`. If this was not the case, then I could make the exact same `deploy` syscall without actually owning the underlying EVM address, thus blocking the true owner of the EVM address to actually use it in kakarot
https://github.com/Flydexo/kakarot-eth-aa/blob/422239b0d65175d1689dba99dddc00734c13ee92/src/kethaa/deployer/deployer.cairo#L47

**Comment by ClementWalter** [comment] 2023-01-02 17:51
Solution 2. looks good to me. Every account on kakarot (EAO, Contract account) consequently has one single underlying _actual_ starknet contract.

Together with the kakarot native token address, all ETH transfers (`payable`, `address.transfer` etc.). are just a transfer between the underlying starknet addresses in the native token.

If this token is indeed the standard ETH token of Starknet, it looks like there is no need for a custom bridge to have ETH on Kakarot

**Comment by ClementWalter** [comment] 2023-01-02 20:06
I have to say that I don't really understand the issue with fees. If the solution 2 is taken, at the end it's like if the user triggers a usual starknet tx so we could just leave this here and let starknet manage fees. And because Kakarot fees would be Starknet ETH (see above) an address getting money from Kakarot would be able to pay tx

**Comment by Eikix** [comment] 2023-01-02 20:31
> I have to say that I don't really understand the issue with fees. If the solution 2 is taken, at the end it's like if the user triggers a usual starknet tx so we could just leave this here and let starknet manage fees. And because Kakarot fees would be Starknet ETH (see above) an address getting money from Kakarot would be able to pay tx

It's about being able to choose max fees at the evm level, someone would send a tx with some gas limit and or max gas priority fee and somehow have this logic incorporated into the starknet tx, even though they're not equivalent.

Otherwise we'd have to set a very high maximum fee in starknet every time regardless of user gas preferences

**Comment by ClementWalter** [comment] 2023-01-02 20:40
> > I have to say that I don't really understand the issue with fees. If the solution 2 is taken, at the end it's like if the user triggers a usual starknet tx so we could just leave this here and let starknet manage fees. And because Kakarot fees would be Starknet ETH (see above) an address getting money from Kakarot would be able to pay tx
> 
> It's about being able to choose max fees at the evm level, someone would send a tx with some gas limit and or max gas priority fee and somehow have this logic incorporated into the starknet tx, even though they're not equivalent.
> 
> Otherwise we'd have to set a very high maximum fee in starknet every time regardless of user gas preferences

I am not sure to understand the difficulty compared to a regular Starknet tx:
1. user crafts the tx
2. fee estimation for tx returned by node/wallet
3. user submit the tx with proper max fee

with Kakarot, we would have 2 actually made of:
a. node crafts the Starknet tx
b. node gets Starknet tx fees estimate
c. node gets evm tx gas used
d. node returns gas_price = fees / gas_used

**Comment by Flydexo** [comment] 2023-01-02 21:03
> > > I have to say that I don't really understand the issue with fees. If the solution 2 is taken, at the end it's like if the user triggers a usual starknet tx so we could just leave this here and let starknet manage fees. And because Kakarot fees would be Starknet ETH (see above) an address getting money from Kakarot would be able to pay tx
> > 
> > 
> > It's about being able to choose max fees at the evm level, someone would send a tx with some gas limit and or max gas priority fee and somehow have this logic incorporated into the starknet tx, even though they're not equivalent.
> > Otherwise we'd have to set a very high maximum fee in starknet every time regardless of user gas preferences
> 
> I am not sure to understand the difficulty compared to a regular Starknet tx:
> 
> 1. user crafts the tx
> 2. fee estimation for tx returned by node/wallet
> 3. user submit the tx with proper max fee
> 
> with Kakarot, we would have 2 actually made of: a. node crafts the Starknet tx b. node gets Starknet tx fees estimate c. node gets evm tx gas used d. node returns gas_price = fees / gas_used

Yes but the problem is not on the wallet, the problem is on the account abstraction. We need to get the fees that will cost the transaction before validating it, because if the user underpaid the fees we need the tx to fail. So it won't use user funds without explicit consent.

**Comment by ClementWalter** [comment] 2023-01-02 21:05
@Flydexo can you detail the difference with a regular tx then? I still don't get it

**Comment by Flydexo** [comment] 2023-01-02 21:09
Let's say I have 5 ETH in my wallet and I sign an evm tx where I acknowledge to pay 0.01 ETH for fees. The Account Abstraction will receive the transaction. Then it needs to compare the actual fees vs the fees the user signed in the tx. If the user provided fees < than actual fees the tx should fail. Because starknet won't know the difference between the user balance (5 ETH) and what it really wanted to spend for fees (0.01 ETH).

**Comment by ClementWalter** [comment] 2023-01-02 21:22
how does the AA know the fees for a usual Starknet tx? At the end, a kakarot tx is a regular Starknet tx so what's the difference?

**Comment by Flydexo** [comment] 2023-01-02 21:31
that's what we need to find out, we need to find out how to calculate the gas cost of a starknet tx from the account abstraction contract

**Comment by ClementWalter** [comment] 2023-01-03 07:23
So I still don’t understand : 
- a kakarot tx is a regular Starknet tx
- As such there’s no fee estimation problem on this part, right?
- The user however wants to specify a ges_price in terms of EVM gas usage 
- The gas_price is then Starknet_fee / gas_usage

**Closed** 2023-01-14 13:16 UTC
Labels: Difficulty: hard, Duration: 1 day, Context: isolated
